# Generated by Django 3.1.3 on 2020-12-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('nombre', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('telefono', models.CharField(default='+56988889999', max_length=25)),
                ('info_req', models.CharField(choices=[('ayuda-dev', '¿Como ayudar a los creadores?'), ('contacto-dev', 'Quiero contactarme con el desarrollador de la pagína')], default='ayuda-dev', max_length=25)),
            ],
        ),
    ]
